### ISSUE TITLE
Verify Login

### ISSUE THREAD

**Issue by jaylenw** [Linux4Hope/Spero-BaasBox#1]
Make sure you can login with Baasbox with the same credentials you would use with the web portal.

This issue will close when everyone is able to do this.
![screenshot from 2017-06-15 20-43-13](https://user-images.githubusercontent.com/6505395/27211134-0259d1e0-520c-11e7-9db1-b232ac721a6b.png)

**Comment by jaylenw** [comment]
please comment once you are able to do this.

**Comment by narithchoeun** [comment]
I was able to get results for my account as well.

**Comment by ghost** [comment]
I got the same results as well.

**Comment by alanlm** [comment]
it works

**Comment by jaylenw** [comment]
Everybody got it working. closing issue.
