### ISSUE TITLE
Get User Profile

### ISSUE THREAD

**Issue by jaylenw** [Linux4Hope/Spero-BaasBox#2]
Get user profile information. Make sure you copy your X-B-session token. The token is how Baasbox authenticates and determines its you.

This issue will close when everyone is able to do this.

Notice there are two ways to do this. One, explicitly using the query parameter in the url or in the header field of postman.

![screenshot from 2017-06-15 20-54-03](https://user-images.githubusercontent.com/6505395/27211305-3c13e780-520d-11e7-8d8e-8a6e55020e25.png)

![screenshot from 2017-06-15 20-54-18](https://user-images.githubusercontent.com/6505395/27211309-3faeb640-520d-11e7-9394-4aa626468264.png)

**Comment by jaylenw** [comment]
please comment once you are able to do this.

**Comment by ghost** [comment]
got it working both ways.

**Comment by alanlm** [comment]
got it to work using /me and /user

**Comment by ghost** [comment]
@alanlm this only deals with /me >:[
