### ISSUE TITLE
Logout User

### ISSUE THREAD

**Issue by jaylenw** [Linux4Hope/Spero-BaasBox#3]
Please comment once you are able to logout a user.

![screenshot from 2017-06-15 20-59-40](https://user-images.githubusercontent.com/6505395/27211368-ac61bfee-520d-11e7-81c4-52a17ec7b61d.png)

**Comment by ghost** [comment]
working GREAT :-)

**Comment by alanlm** [comment]
i logged out. I also did it without the appcode just with the x-bb-session

**Comment by jaylenw** [comment]
no app code needed. @alanlm

**Comment by jaylenw** [comment]
@narithchoeun  set so i can close?
