### ISSUE TITLE
Signup User

### ISSUE THREAD

**Issue by jaylenw** [Linux4Hope/Spero-BaasBox#4]
Perform a user signup. This issue will close once everyone is able to do it.

Please comment when you have performed this action. Once you create the user, dont forget to logout that same user you created using postman. As a bonus, try and suspend and activate the user you just created with postman.

After you are done, make sure to suspend the user for now either through postman or the web console.

![screenshot from 2017-06-15 21-57-31](https://user-images.githubusercontent.com/6505395/27212701-b3618e6a-5216-11e7-859d-6d9ba495ab1b.png)

**Comment by ghost** [comment]
created user and logged out same user complete. still working on suspend and re-activate (might not get to this until tomorrow).

**Comment by alanlm** [comment]
okay i created, suspended, and reactivated a user

**Comment by ghost** [comment]
suspended, reactivated, and logged out.
