### ISSUE TITLE
Implement & Test Reset Password

### ISSUE THREAD

**Issue by jaylenw** [Linux4Hope/Spero-BaasBox#6]
Reset password functionality for registered users. Depends on issue #5

**Comment by jaylenw** [comment]
Initial test of reset password works but need to fix the localhost url.

![screenshot from 2017-06-20 02-03-29](https://user-images.githubusercontent.com/6505395/27325414-349bb2f0-555d-11e7-934b-1afbc9b9a63e.png)

**Comment by alanlm** [comment]
got the password reset link to work 
![image](https://user-images.githubusercontent.com/14934383/27327706-47411560-5564-11e7-81af-b73f33e92af1.png)

**Comment by ghost** [comment]
@alanlm wouldn't you want them to type in their old password along with their new password as a verification?

**Comment by jaylenw** [comment]
@nguym077 This is for case where the user forgot their current password. But you reminded me that what you mention would be the case when a user would like to change their password to a new one.

**Comment by jaylenw** [comment]
Was able to reset a user's password and then login in with the new password to make sure it works.

![screenshot from 2017-06-21 22-40-16](https://user-images.githubusercontent.com/6505395/27418925-ecfa5b46-56d2-11e7-957f-c03030b34cdb.png)
