### ISSUE TITLE
Retrieve all documents from Collection

### ISSUE THREAD

**Issue by jaylenw** [Linux4Hope/Spero-BaasBox#8]
Please make sure you are able to do this. Comment once completed.

![screenshot from 2017-06-19 23-43-12](https://user-images.githubusercontent.com/6505395/27320015-2752e96a-5549-11e7-8834-ea8edad1cf17.png)

**Comment by ghost** [comment]
got it working. What exactly is "collection"? @jaylenw

**Comment by jaylenw** [comment]
@nguym077 A collection is like a table and a document is like a row
